### PR TITLE
Implement stop/start connector

### PR DESCRIPTION
**Pull request by lgarciaaco**
Making use of the public endpoint PATCH "/v1/kafka_connectors/${connector_id}", implement access to it from the rhoc cli

### CODE REVIEW

**Comment by heiko-braun** [comment]
I think we would need to create a sparate Admin endpoint for this, no? Otherwise you can only manage your own connectors through the `rhoc` CLI, rather than connectors that belong to other users (which is the whole point of `rhoc`)

**Comment by valdar** [comment]
I fear that partial of the confusion of this is my fault. I didn't get the whole use case so I might have given non so coherent info. Apologies for that.

I fear that the creation of an endpoint under `admin/` part of the api is unavoidable. Furthermore this endpoint should just expose the start/stop functionality and not the whole container PATCH mechanism to the admin user.

**Comment by heiko-braun** [comment]
Looks like you owe @lgarciaaco a beer

**Comment by lgarciaaco** [comment]
Yea it was confusing because there is a public endpoint doing just that, my hope was that we could use the existing public endpoint but now it is clear that it is not possible. Thanks for the input!

**Pull request closed without merging**
