### PR TITLE
chore(rhoc): updated openapi for resource annotations

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@lburgazzoli do we need to show annotations in connector types as another column?

**Comment by lburgazzoli** [comment]
we can try but the output may become very large

**Comment by dhirajsb** [comment]
That's what I was thinking too. At least with this update we can now see the annotations in json/yaml output.

**Comment by lburgazzoli** [comment]
I'll trigger a new release

**Pull request merged**
